Repository umccr/libica, pull requests merged in 2023-02, with the labels that each got.

#79 Dropped Python 3.6 support
  .github/workflows/prbuild.yml
  setup.py
  tox.ini
Labels: dependencies

#80 Updated ICAv1 Swagger definition 20230216
  setup.py
  swagger/ens.json
  swagger/gds.json
  swagger/tes.json
  swagger/wes.json
Labels: upstream, ICAv1

#81 Updated ICAv2 OpenAPI definition 20230216
  swagger/openapi_public.yaml
Labels: upstream, ICAv2

#83 Sweep ICAv2 OpenAPI 204 empty content
  swagger/openapi_public.yaml
Labels: fix, upstream, ICAv2

#85 Improved test cases
  tests/app/test_gds.py
  tests/app/test_wes.py
  tests/test_libwes.py
Labels: fix

#86 Fixed OpenAPI analysisPriority value mismatch with server response
  libica/openapi/v2/model/analysis.py
  libica/openapi/v2/model/create_project.py
  libica/openapi/v2/model/project.py
Labels: bug, fix, ICAv2

#87 Added examples directory for demo scripts
  README.md
  examples/get_activation_id.py
  examples/pilot.py
  examples/pilotapp.py
  openapi/docs/app/README.md
Labels: documentation

#88 Updated to use across env var ICAV2_PROJECT_ID
  examples/pilot.py
  examples/pilotapp.py
  libica/app/__init__.py
Labels: documentation, fix

#89 Support Content-Disposition Config on PresignedUrl
  examples/gds.py
  libica/app/gds.py
Labels: feature

#90 Added support for POST form field filename settable
  libica/openapi/v2/api_client.py
  libica/openapi/v2/configuration.py
Labels: feature

#91 Added ICA v2 create CWL pipeline example using tabix workflow
  examples/create_cwl_pipeline.py
  examples/gds_app_script.py
  examples/gds_list_files.py
  examples/tabix-workflow__0.2.6__1677025399/params.xml
  examples/tabix-workflow__0.2.6__1677025399/tools/tabix/0.2.6/tabix__0.2.6.cwl
  examples/tabix-workflow__0.2.6__1677025399/workflow.cwl
  libica/app/gds.py
Labels: documentation

#93 Minor refactored tests
  tests/v1/__init__.py
  tests/v1/test_libwes.py
  tests/v2/__init__.py
  tests/v2/test_project.py
Labels: fix
